SRC = cbe.cpp component_e.cpp 
      

INCLUDES= -I ..

include ../config.inc
include ../common

CLEANFILES = cbe$(LIBEXT) component_e$(LIBEXT)

all: cbe$(LIBEXT) 

###############################################################################

cbe$(LIBEXT): $(OBJ)
	$(LINKLIB)



